/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : lenovo
 * Created : 11/14/2013
 */

package com.user.buuluu.service.test;

import org.junit.Before;
import org.junit.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.user.buuluu.common.util.Constant;
import com.user.buuluu.model.User;
import com.user.buuluu.service.UserService;


public class APITestServiceImplTest{

	private UserService userService;
     
         /**
	      * 这个before方法在所有的测试方法之前执行，并且只执行一次
	      * 所有做Junit单元测试时一些初始化工作可以在这个方法里面进行
	      * 比如在before方法里面初始化ApplicationContext和userService
	      */
	     @Before
	     public void before(){
	         //使用"spring.xml"和"spring-mybatis.xml"这两个配置文件创建Spring上下文
	         ApplicationContext ac = new ClassPathXmlApplicationContext(new String[]{"application-context.xml"});
	         //从Spring容器中根据bean的id取出我们要使用的userService对象
	         userService = (UserService) ac.getBean("userService");
	     }
	     
	     @Test
	     public void testAddUser(){
	         //ApplicationContext ac = new ClassPathXmlApplicationContext(new String[]{"spring.xml","spring-mybatis.xml"});
	        //UserServiceI userService = (UserServiceI) ac.getBean("userService");
	         User user = new User();
	         user.setId(Constant.getUserId());
	         user.setBirthday("123213");
	         user.setCountry("12121212");
	         userService.addUser(user,user.getId());
	     }
}
