-- ----------------------------
-- before set all tables,set fk_checks
-- ----------------------------
SET FOREIGN_KEY_CHECKS = 0;
-- ----------------------------
-- Table structure for `APP_USER  `
-- ----------------------------
DROP TABLE IF EXISTS `APP_BUULUU_USER`;
CREATE TABLE `APP_BUULUU_USER` (
  `ID` VARCHAR(100) CHARACTER SET utf8 NOT NULL,
   `TOKEN` VARCHAR(100) DEFAULT NULL,
  `LOGIN_TYPE` INT(1) DEFAULT NULL,
  `LOGIN_TIME` DATETIME DEFAULT NULL,
  `LOGOUT_TIME` DATETIME DEFAULT NULL,
  `LANG` VARCHAR(10) DEFAULT NULL,
  `DEVICE` VARCHAR(1) DEFAULT NULL,
  `DEVICE_VER_NUM` VARCHAR(10) DEFAULT NULL,
  `IMEI` VARCHAR(20) DEFAULT NULL,
  `MAC` VARCHAR(20) DEFAULT NULL,
   `IMSI` VARCHAR(20) DEFAULT NULL,
  `STATUS` INT(1) DEFAULT NULL,
  `CREATED_BY` VARCHAR(45) DEFAULT NULL,
  `CREATED_TIME` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(45) DEFAULT NULL,
  `UPDATED_TIME` DATETIME DEFAULT NULL,
  `IS_DELETED` INT(1) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_VISTOR_USER`;
CREATE TABLE `APP_VISTOR_USER` (
  `ID` VARCHAR(100) CHARACTER SET utf8 NOT NULL,
  `NICK_NAME` VARCHAR(30) CHARACTER SET utf8 DEFAULT '',
  `ICON` VARCHAR(100) CHARACTER SET utf8 DEFAULT '',
  `PWD` VARCHAR(150) CHARACTER SET utf8 DEFAULT NULL,
  `TEL` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
  `COUNTRY_CODE` VARCHAR(5) DEFAULT '',
  `TEL_APPROVE_KEY` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL,
  `COUNTRY` VARCHAR(10) CHARACTER SET utf8 DEFAULT '',
  `TEL_VALUE_FLAG` INT(1) DEFAULT '0',
  `BIRTHDAY` LONG DEFAULT NULL,
  `SEX` INT(2)  DEFAULT '1',
  `PUSH_STATUS` INT(1),
  `LOG` DOUBLE DEFAULT NULL,
  `LAT` DOUBLE DEFAULT NULL,
  `FLOW_COINS` FLOAT DEFAULT '0',
  `MAKE_FLOW` FLOAT DEFAULT '0',
  `USER_FLOW` FLOAT DEFAULT '0',
   `POINT` INT DEFAULT '0',
   `CREDIT` INT DEFAULT '0',
  `CREATED_BY` VARCHAR(45) CHARACTER SET utf8 DEFAULT NULL,
  `CREATED_TIME` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(45) CHARACTER SET utf8 DEFAULT NULL,
  `UPDATED_TIME` DATETIME DEFAULT NULL,
  `IS_DELETED` INT(1) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- after set all tables,set fk_checks
-- ----------------------------
SET FOREIGN_KEY_CHECKS = 1;
