package com.user.buuluu.model;

import java.io.Serializable;

public class AdVideoWithBLOBs extends AdVideo implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5664863284640509504L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.title
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.picture
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.tinyPicture
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String tinypicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.description
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.videoUrl
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String videourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.activityDesc
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String activitydesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.title
     *
     * @return the value of ad_video.title
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.title
     *
     * @param title the value for ad_video.title
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.picture
     *
     * @return the value of ad_video.picture
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.picture
     *
     * @param picture the value for ad_video.picture
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.tinyPicture
     *
     * @return the value of ad_video.tinyPicture
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getTinypicture() {
        return tinypicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.tinyPicture
     *
     * @param tinypicture the value for ad_video.tinyPicture
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setTinypicture(String tinypicture) {
        this.tinypicture = tinypicture == null ? null : tinypicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.description
     *
     * @return the value of ad_video.description
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.description
     *
     * @param description the value for ad_video.description
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.videoUrl
     *
     * @return the value of ad_video.videoUrl
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.videoUrl
     *
     * @param videourl the value for ad_video.videoUrl
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.activityDesc
     *
     * @return the value of ad_video.activityDesc
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getActivitydesc() {
        return activitydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.activityDesc
     *
     * @param activitydesc the value for ad_video.activityDesc
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setActivitydesc(String activitydesc) {
        this.activitydesc = activitydesc == null ? null : activitydesc.trim();
    }
}