package com.user.buuluu.model;

public class AdVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.id
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.categoryId
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private Integer categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.createTime
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.expireTime
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private String expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_video.flowCoins
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    private Integer flowcoins;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.id
     *
     * @return the value of ad_video.id
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.id
     *
     * @param id the value for ad_video.id
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.categoryId
     *
     * @return the value of ad_video.categoryId
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.categoryId
     *
     * @param categoryid the value for ad_video.categoryId
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.createTime
     *
     * @return the value of ad_video.createTime
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.createTime
     *
     * @param createtime the value for ad_video.createTime
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.expireTime
     *
     * @return the value of ad_video.expireTime
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public String getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.expireTime
     *
     * @param expiretime the value for ad_video.expireTime
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setExpiretime(String expiretime) {
        this.expiretime = expiretime == null ? null : expiretime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_video.flowCoins
     *
     * @return the value of ad_video.flowCoins
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public Integer getFlowcoins() {
        return flowcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_video.flowCoins
     *
     * @param flowcoins the value for ad_video.flowCoins
     *
     * @mbggenerated Mon Aug 24 11:03:56 CST 2015
     */
    public void setFlowcoins(Integer flowcoins) {
        this.flowcoins = flowcoins;
    }
}