package com.user.buuluu.model;

import java.io.Serializable;
import java.util.Date;

public class AppBuuluuUser implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8379379477559394168L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.ID
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.TOKEN
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.LOGIN_TYPE
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Integer loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.LOGIN_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.LOGOUT_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Date logoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.LANG
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.DEVICE
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.DEVICE_VER_NUM
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String deviceVerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.IMEI
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.MAC
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.IMSI
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String imsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.STATUS
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.CREATED_BY
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.CREATED_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.UPDATED_BY
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.UPDATED_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_buuluu_user.IS_DELETED
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.ID
     *
     * @return the value of app_buuluu_user.ID
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.ID
     *
     * @param id the value for app_buuluu_user.ID
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.TOKEN
     *
     * @return the value of app_buuluu_user.TOKEN
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.TOKEN
     *
     * @param token the value for app_buuluu_user.TOKEN
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.LOGIN_TYPE
     *
     * @return the value of app_buuluu_user.LOGIN_TYPE
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.LOGIN_TYPE
     *
     * @param loginType the value for app_buuluu_user.LOGIN_TYPE
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.LOGIN_TIME
     *
     * @return the value of app_buuluu_user.LOGIN_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.LOGIN_TIME
     *
     * @param loginTime the value for app_buuluu_user.LOGIN_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.LOGOUT_TIME
     *
     * @return the value of app_buuluu_user.LOGOUT_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.LOGOUT_TIME
     *
     * @param logoutTime the value for app_buuluu_user.LOGOUT_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.LANG
     *
     * @return the value of app_buuluu_user.LANG
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.LANG
     *
     * @param lang the value for app_buuluu_user.LANG
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.DEVICE
     *
     * @return the value of app_buuluu_user.DEVICE
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.DEVICE
     *
     * @param device the value for app_buuluu_user.DEVICE
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.DEVICE_VER_NUM
     *
     * @return the value of app_buuluu_user.DEVICE_VER_NUM
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getDeviceVerNum() {
        return deviceVerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.DEVICE_VER_NUM
     *
     * @param deviceVerNum the value for app_buuluu_user.DEVICE_VER_NUM
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setDeviceVerNum(String deviceVerNum) {
        this.deviceVerNum = deviceVerNum == null ? null : deviceVerNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.IMEI
     *
     * @return the value of app_buuluu_user.IMEI
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.IMEI
     *
     * @param imei the value for app_buuluu_user.IMEI
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.MAC
     *
     * @return the value of app_buuluu_user.MAC
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.MAC
     *
     * @param mac the value for app_buuluu_user.MAC
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.IMSI
     *
     * @return the value of app_buuluu_user.IMSI
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.IMSI
     *
     * @param imsi the value for app_buuluu_user.IMSI
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.STATUS
     *
     * @return the value of app_buuluu_user.STATUS
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.STATUS
     *
     * @param status the value for app_buuluu_user.STATUS
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.CREATED_BY
     *
     * @return the value of app_buuluu_user.CREATED_BY
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.CREATED_BY
     *
     * @param createdBy the value for app_buuluu_user.CREATED_BY
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.CREATED_TIME
     *
     * @return the value of app_buuluu_user.CREATED_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.CREATED_TIME
     *
     * @param createdTime the value for app_buuluu_user.CREATED_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.UPDATED_BY
     *
     * @return the value of app_buuluu_user.UPDATED_BY
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.UPDATED_BY
     *
     * @param updatedBy the value for app_buuluu_user.UPDATED_BY
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.UPDATED_TIME
     *
     * @return the value of app_buuluu_user.UPDATED_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.UPDATED_TIME
     *
     * @param updatedTime the value for app_buuluu_user.UPDATED_TIME
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_buuluu_user.IS_DELETED
     *
     * @return the value of app_buuluu_user.IS_DELETED
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_buuluu_user.IS_DELETED
     *
     * @param isDeleted the value for app_buuluu_user.IS_DELETED
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}