package com.user.buuluu.model;

import java.io.Serializable;
import java.util.Date;

public class AppBillReord implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8818538213605060583L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.ID
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.TYPE
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.STATUS
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.MAKE_FLOWS
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Float makeFlows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.DESCRIPTION
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.USER_ID
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.CREATED_TIME
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.UPDATED_BY
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.UPDATED_TIME
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_bill_record.IS_DELETED
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.ID
     *
     * @return the value of app_bill_record.ID
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.ID
     *
     * @param id the value for app_bill_record.ID
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.TYPE
     *
     * @return the value of app_bill_record.TYPE
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.TYPE
     *
     * @param type the value for app_bill_record.TYPE
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.STATUS
     *
     * @return the value of app_bill_record.STATUS
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.STATUS
     *
     * @param status the value for app_bill_record.STATUS
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.MAKE_FLOWS
     *
     * @return the value of app_bill_record.MAKE_FLOWS
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Float getMakeFlows() {
        return makeFlows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.MAKE_FLOWS
     *
     * @param makeFlows the value for app_bill_record.MAKE_FLOWS
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setMakeFlows(Float makeFlows) {
        this.makeFlows = makeFlows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.DESCRIPTION
     *
     * @return the value of app_bill_record.DESCRIPTION
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.DESCRIPTION
     *
     * @param description the value for app_bill_record.DESCRIPTION
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.USER_ID
     *
     * @return the value of app_bill_record.USER_ID
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.USER_ID
     *
     * @param userId the value for app_bill_record.USER_ID
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.CREATED_TIME
     *
     * @return the value of app_bill_record.CREATED_TIME
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.CREATED_TIME
     *
     * @param createdTime the value for app_bill_record.CREATED_TIME
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.UPDATED_BY
     *
     * @return the value of app_bill_record.UPDATED_BY
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.UPDATED_BY
     *
     * @param updatedBy the value for app_bill_record.UPDATED_BY
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.UPDATED_TIME
     *
     * @return the value of app_bill_record.UPDATED_TIME
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.UPDATED_TIME
     *
     * @param updatedTime the value for app_bill_record.UPDATED_TIME
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_bill_record.IS_DELETED
     *
     * @return the value of app_bill_record.IS_DELETED
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_bill_record.IS_DELETED
     *
     * @param isDeleted the value for app_bill_record.IS_DELETED
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}