package com.user.buuluu.model;

import java.util.Date;

public class AppFlowPackage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.ID
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.CREATED_BY
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.CREATED_TIME
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.UPDATED_BY
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.UPDATED_TIME
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.IS_DELETED
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.FLOW_COINS
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private Integer flowCoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flow_package.EXPIRE_DATE
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    private Integer expireDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.ID
     *
     * @return the value of app_flow_package.ID
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.ID
     *
     * @param id the value for app_flow_package.ID
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.CREATED_BY
     *
     * @return the value of app_flow_package.CREATED_BY
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.CREATED_BY
     *
     * @param createdBy the value for app_flow_package.CREATED_BY
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.CREATED_TIME
     *
     * @return the value of app_flow_package.CREATED_TIME
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.CREATED_TIME
     *
     * @param createdTime the value for app_flow_package.CREATED_TIME
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.UPDATED_BY
     *
     * @return the value of app_flow_package.UPDATED_BY
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.UPDATED_BY
     *
     * @param updatedBy the value for app_flow_package.UPDATED_BY
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.UPDATED_TIME
     *
     * @return the value of app_flow_package.UPDATED_TIME
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.UPDATED_TIME
     *
     * @param updatedTime the value for app_flow_package.UPDATED_TIME
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.IS_DELETED
     *
     * @return the value of app_flow_package.IS_DELETED
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.IS_DELETED
     *
     * @param isDeleted the value for app_flow_package.IS_DELETED
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.FLOW_COINS
     *
     * @return the value of app_flow_package.FLOW_COINS
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public Integer getFlowCoins() {
        return flowCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.FLOW_COINS
     *
     * @param flowCoins the value for app_flow_package.FLOW_COINS
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setFlowCoins(Integer flowCoins) {
        this.flowCoins = flowCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flow_package.EXPIRE_DATE
     *
     * @return the value of app_flow_package.EXPIRE_DATE
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public Integer getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flow_package.EXPIRE_DATE
     *
     * @param expireDate the value for app_flow_package.EXPIRE_DATE
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    public void setExpireDate(Integer expireDate) {
        this.expireDate = expireDate;
    }
}