package com.user.buuluu.model;

import java.io.Serializable;

public class AppInfo implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5181936892799346939L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.rowid
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.pkgName
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String pkgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.name
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.author
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.version
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.versionCode
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String versioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.apkSizeRaw
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer apksizeraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.price
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.downloadTimes
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer downloadtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.updateTime
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.minSdkVersion
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer minsdkversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.stars
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String stars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.starScore
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Float starscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.countryCode
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String countrycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.classId
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.flowCoins
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer flowcoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.shareCoins
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer sharecoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.sourceFlag
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private Integer sourceflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.rowid
     *
     * @return the value of app_info.rowid
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.rowid
     *
     * @param rowid the value for app_info.rowid
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setRowid(Integer rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.pkgName
     *
     * @return the value of app_info.pkgName
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getPkgname() {
        return pkgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.pkgName
     *
     * @param pkgname the value for app_info.pkgName
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setPkgname(String pkgname) {
        this.pkgname = pkgname == null ? null : pkgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.name
     *
     * @return the value of app_info.name
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.name
     *
     * @param name the value for app_info.name
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.author
     *
     * @return the value of app_info.author
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.author
     *
     * @param author the value for app_info.author
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.version
     *
     * @return the value of app_info.version
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.version
     *
     * @param version the value for app_info.version
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.versionCode
     *
     * @return the value of app_info.versionCode
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getVersioncode() {
        return versioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.versionCode
     *
     * @param versioncode the value for app_info.versionCode
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setVersioncode(String versioncode) {
        this.versioncode = versioncode == null ? null : versioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.apkSizeRaw
     *
     * @return the value of app_info.apkSizeRaw
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getApksizeraw() {
        return apksizeraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.apkSizeRaw
     *
     * @param apksizeraw the value for app_info.apkSizeRaw
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setApksizeraw(Integer apksizeraw) {
        this.apksizeraw = apksizeraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.price
     *
     * @return the value of app_info.price
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.price
     *
     * @param price the value for app_info.price
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.downloadTimes
     *
     * @return the value of app_info.downloadTimes
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getDownloadtimes() {
        return downloadtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.downloadTimes
     *
     * @param downloadtimes the value for app_info.downloadTimes
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setDownloadtimes(Integer downloadtimes) {
        this.downloadtimes = downloadtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.updateTime
     *
     * @return the value of app_info.updateTime
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.updateTime
     *
     * @param updatetime the value for app_info.updateTime
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.minSdkVersion
     *
     * @return the value of app_info.minSdkVersion
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getMinsdkversion() {
        return minsdkversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.minSdkVersion
     *
     * @param minsdkversion the value for app_info.minSdkVersion
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setMinsdkversion(Integer minsdkversion) {
        this.minsdkversion = minsdkversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.stars
     *
     * @return the value of app_info.stars
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.stars
     *
     * @param stars the value for app_info.stars
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setStars(String stars) {
        this.stars = stars == null ? null : stars.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.starScore
     *
     * @return the value of app_info.starScore
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Float getStarscore() {
        return starscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.starScore
     *
     * @param starscore the value for app_info.starScore
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setStarscore(Float starscore) {
        this.starscore = starscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.countryCode
     *
     * @return the value of app_info.countryCode
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.countryCode
     *
     * @param countrycode the value for app_info.countryCode
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.classId
     *
     * @return the value of app_info.classId
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.classId
     *
     * @param classid the value for app_info.classId
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.flowCoins
     *
     * @return the value of app_info.flowCoins
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getFlowcoins() {
        return flowcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.flowCoins
     *
     * @param flowcoins the value for app_info.flowCoins
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setFlowcoins(Integer flowcoins) {
        this.flowcoins = flowcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.shareCoins
     *
     * @return the value of app_info.shareCoins
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getSharecoins() {
        return sharecoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.shareCoins
     *
     * @param sharecoins the value for app_info.shareCoins
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setSharecoins(Integer sharecoins) {
        this.sharecoins = sharecoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.sourceFlag
     *
     * @return the value of app_info.sourceFlag
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public Integer getSourceflag() {
        return sourceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.sourceFlag
     *
     * @param sourceflag the value for app_info.sourceFlag
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setSourceflag(Integer sourceflag) {
        this.sourceflag = sourceflag;
    }
}