package com.user.buuluu.model;

public class AppInfoWithBLOBs extends AppInfo {
    /**
	 * 
	 */
	private static final long serialVersionUID = -6629791379107612004L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.downloadURL
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String downloadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.iconURL
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String iconurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.description
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.screenshot
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String screenshot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.smallPic
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String smallpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.overview
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String overview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.whatsNew
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String whatsnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.identifierFlag
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String identifierflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.instruction
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    private String instruction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.downloadURL
     *
     * @return the value of app_info.downloadURL
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getDownloadurl() {
        return downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.downloadURL
     *
     * @param downloadurl the value for app_info.downloadURL
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl == null ? null : downloadurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.iconURL
     *
     * @return the value of app_info.iconURL
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getIconurl() {
        return iconurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.iconURL
     *
     * @param iconurl the value for app_info.iconURL
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setIconurl(String iconurl) {
        this.iconurl = iconurl == null ? null : iconurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.description
     *
     * @return the value of app_info.description
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.description
     *
     * @param description the value for app_info.description
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.screenshot
     *
     * @return the value of app_info.screenshot
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getScreenshot() {
        return screenshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.screenshot
     *
     * @param screenshot the value for app_info.screenshot
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setScreenshot(String screenshot) {
        this.screenshot = screenshot == null ? null : screenshot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.smallPic
     *
     * @return the value of app_info.smallPic
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getSmallpic() {
        return smallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.smallPic
     *
     * @param smallpic the value for app_info.smallPic
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setSmallpic(String smallpic) {
        this.smallpic = smallpic == null ? null : smallpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.overview
     *
     * @return the value of app_info.overview
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.overview
     *
     * @param overview the value for app_info.overview
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.whatsNew
     *
     * @return the value of app_info.whatsNew
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getWhatsnew() {
        return whatsnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.whatsNew
     *
     * @param whatsnew the value for app_info.whatsNew
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setWhatsnew(String whatsnew) {
        this.whatsnew = whatsnew == null ? null : whatsnew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.identifierFlag
     *
     * @return the value of app_info.identifierFlag
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getIdentifierflag() {
        return identifierflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.identifierFlag
     *
     * @param identifierflag the value for app_info.identifierFlag
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setIdentifierflag(String identifierflag) {
        this.identifierflag = identifierflag == null ? null : identifierflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.instruction
     *
     * @return the value of app_info.instruction
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.instruction
     *
     * @param instruction the value for app_info.instruction
     *
     * @mbggenerated Mon Aug 24 12:06:12 CST 2015
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }
}