package com.user.buuluu.model;

import java.io.Serializable;
import java.util.Date;

public class AppScratch implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.ID
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.IMG
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.FLOW_COINS
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private Float flowCoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.DESCRIPTION
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.CREATED_TIME
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.UPDATED_BY
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.UPDATED_TIME
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_scratch.IS_DELETED
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.ID
     *
     * @return the value of app_scratch.ID
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.ID
     *
     * @param id the value for app_scratch.ID
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.IMG
     *
     * @return the value of app_scratch.IMG
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.IMG
     *
     * @param img the value for app_scratch.IMG
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.FLOW_COINS
     *
     * @return the value of app_scratch.FLOW_COINS
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public Float getFlowCoins() {
        return flowCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.FLOW_COINS
     *
     * @param flowCoins the value for app_scratch.FLOW_COINS
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setFlowCoins(Float flowCoins) {
        this.flowCoins = flowCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.DESCRIPTION
     *
     * @return the value of app_scratch.DESCRIPTION
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.DESCRIPTION
     *
     * @param description the value for app_scratch.DESCRIPTION
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.CREATED_TIME
     *
     * @return the value of app_scratch.CREATED_TIME
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.CREATED_TIME
     *
     * @param createdTime the value for app_scratch.CREATED_TIME
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.UPDATED_BY
     *
     * @return the value of app_scratch.UPDATED_BY
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.UPDATED_BY
     *
     * @param updatedBy the value for app_scratch.UPDATED_BY
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.UPDATED_TIME
     *
     * @return the value of app_scratch.UPDATED_TIME
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.UPDATED_TIME
     *
     * @param updatedTime the value for app_scratch.UPDATED_TIME
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_scratch.IS_DELETED
     *
     * @return the value of app_scratch.IS_DELETED
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_scratch.IS_DELETED
     *
     * @param isDeleted the value for app_scratch.IS_DELETED
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}