package com.user.buuluu.model;

import java.io.Serializable;
import java.util.Date;

public class AppUserBillLog implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.BILL_ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Long billId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.FLOW_COINS
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Integer flowCoins;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.USER_COIN
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Integer userCoin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.DESCRIPTION
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.USER_ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.CREATED_BY
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.CREATED_TIME
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.UPDATED_BY
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.UPDATED_TIME
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Date updatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_user_bill_log.IS_DELETED
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	private Integer isDeleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.ID
	 * @return  the value of app_user_bill_log.ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.ID
	 * @param id  the value for app_user_bill_log.ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.BILL_ID
	 * @return  the value of app_user_bill_log.BILL_ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Long getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.BILL_ID
	 * @param billId  the value for app_user_bill_log.BILL_ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setBillId(Long billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.FLOW_COINS
	 * @return  the value of app_user_bill_log.FLOW_COINS
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Integer getFlowCoins() {
		return flowCoins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.FLOW_COINS
	 * @param flowCoins  the value for app_user_bill_log.FLOW_COINS
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setFlowCoins(Integer flowCoins) {
		this.flowCoins = flowCoins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.USER_COIN
	 * @return  the value of app_user_bill_log.USER_COIN
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Integer getUserCoin() {
		return userCoin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.USER_COIN
	 * @param userCoin  the value for app_user_bill_log.USER_COIN
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setUserCoin(Integer userCoin) {
		this.userCoin = userCoin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.DESCRIPTION
	 * @return  the value of app_user_bill_log.DESCRIPTION
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.DESCRIPTION
	 * @param description  the value for app_user_bill_log.DESCRIPTION
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.USER_ID
	 * @return  the value of app_user_bill_log.USER_ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.USER_ID
	 * @param userId  the value for app_user_bill_log.USER_ID
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.CREATED_BY
	 * @return  the value of app_user_bill_log.CREATED_BY
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.CREATED_BY
	 * @param createdBy  the value for app_user_bill_log.CREATED_BY
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.CREATED_TIME
	 * @return  the value of app_user_bill_log.CREATED_TIME
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.CREATED_TIME
	 * @param createdTime  the value for app_user_bill_log.CREATED_TIME
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.UPDATED_BY
	 * @return  the value of app_user_bill_log.UPDATED_BY
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.UPDATED_BY
	 * @param updatedBy  the value for app_user_bill_log.UPDATED_BY
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy == null ? null : updatedBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.UPDATED_TIME
	 * @return  the value of app_user_bill_log.UPDATED_TIME
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.UPDATED_TIME
	 * @param updatedTime  the value for app_user_bill_log.UPDATED_TIME
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_user_bill_log.IS_DELETED
	 * @return  the value of app_user_bill_log.IS_DELETED
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_user_bill_log.IS_DELETED
	 * @param isDeleted  the value for app_user_bill_log.IS_DELETED
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -1589455144201985217L;
}