package com.user.buuluu.dao.mapper;

import org.springframework.stereotype.Component;

import com.user.buuluu.annotation.MyBatisRepository;
import com.user.buuluu.model.AppBuuluuUser;

@Component
@MyBatisRepository
public interface AppBuuluuUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_buuluu_user
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_buuluu_user
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    int insert(AppBuuluuUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_buuluu_user
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    int insertSelective(AppBuuluuUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_buuluu_user
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    AppBuuluuUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_buuluu_user
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    int updateByPrimaryKeySelective(AppBuuluuUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_buuluu_user
     *
     * @mbggenerated Tue Aug 25 15:34:40 CST 2015
     */
    int updateByPrimaryKey(AppBuuluuUser record);
}