package com.user.buuluu.dao.mapper;

import org.springframework.stereotype.Component;

import com.user.buuluu.annotation.MyBatisRepository;
import com.user.buuluu.model.AppBillReord;

@Component
@MyBatisRepository
public interface AppBillReordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_bill_record
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_bill_record
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    int insert(AppBillReord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_bill_record
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    int insertSelective(AppBillReord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_bill_record
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    AppBillReord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_bill_record
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    int updateByPrimaryKeySelective(AppBillReord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_bill_record
     *
     * @mbggenerated Mon Aug 24 11:01:08 CST 2015
     */
    int updateByPrimaryKey(AppBillReord record);
}