package com.user.buuluu.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Component;

import com.user.buuluu.annotation.MyBatisRepository;
import com.user.buuluu.model.AppFlowPackage;
@Component
@MyBatisRepository
public interface AppFlowPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flow_package
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flow_package
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    int insert(AppFlowPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flow_package
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    int insertSelective(AppFlowPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flow_package
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    AppFlowPackage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flow_package
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    int updateByPrimaryKeySelective(AppFlowPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flow_package
     *
     * @mbggenerated Tue Sep 08 14:36:50 CST 2015
     */
    int updateByPrimaryKey(AppFlowPackage record);

	List<AppFlowPackage> getFlowPkg();
}