package com.user.buuluu.dao.mapper;

import org.springframework.stereotype.Component;

import com.user.buuluu.annotation.MyBatisRepository;
import com.user.buuluu.model.AppScratch;
@Component
@MyBatisRepository
public interface AppScratchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_scratch
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_scratch
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    int insert(AppScratch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_scratch
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    int insertSelective(AppScratch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_scratch
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    AppScratch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_scratch
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    int updateByPrimaryKeySelective(AppScratch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_scratch
     *
     * @mbggenerated Tue Sep 08 12:07:28 CST 2015
     */
    
    AppScratch getScratchCoins(Integer scratchId);
}