package com.user.buuluu.dao.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.user.buuluu.annotation.MyBatisRepository;
import com.user.buuluu.model.AppUserScratch;
import com.user.buuluu.service.model.AppUserScratchModel;
@Component
@MyBatisRepository
public interface AppUserScratchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_scratch
     *
     * @mbggenerated Tue Sep 08 12:09:04 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_scratch
     *
     * @mbggenerated Tue Sep 08 12:09:04 CST 2015
     */
    int insert(AppUserScratch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_scratch
     *
     * @mbggenerated Tue Sep 08 12:09:04 CST 2015
     */
    int insertSelective(AppUserScratch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_scratch
     *
     * @mbggenerated Tue Sep 08 12:09:04 CST 2015
     */
    AppUserScratch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_scratch
     *
     * @mbggenerated Tue Sep 08 12:09:04 CST 2015
     */
    int updateByPrimaryKeySelective(AppUserScratch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_scratch
     *
     * @mbggenerated Tue Sep 08 12:09:04 CST 2015
     */
    
	List<AppUserScratch> getUserScratch(Map<String, Object> map);
	
	List<AppUserScratch> getScratchList();

	List<AppUserScratchModel> getScratchNews(Integer number);
}