package com.user.buuluu.dao.mapper;

import org.springframework.stereotype.Component;

import com.user.buuluu.annotation.MyBatisRepository;
import com.user.buuluu.model.AppUserBillLog;

@Component
@MyBatisRepository
public interface AppUserBillLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_user_bill_log
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_user_bill_log
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	int insert(AppUserBillLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_user_bill_log
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	int insertSelective(AppUserBillLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_user_bill_log
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	AppUserBillLog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_user_bill_log
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	int updateByPrimaryKeySelective(AppUserBillLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_user_bill_log
	 * @mbggenerated  Wed Aug 26 15:59:23 CST 2015
	 */
	int updateByPrimaryKey(AppUserBillLog record);
}